import Footer from "@/components/common/Footer";
import Wrapper from "@/components/common/wrapper";
import ReduxStoreProvider from "@/context-provider/ReduxStoreProvider";
import type { Metadata } from "next";
import { Inter, Roboto, Roboto_Slab } from "next/font/google";
import { Toaster } from "react-hot-toast";

import Header from "@/components/common/Header";
import "swiper/css";
import "./globals.css";
export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});
export const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-roboto",
});
export const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-roboto-slab",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}  antialiased`}
        suppressHydrationWarning
      >
        <Toaster />
        <ReduxStoreProvider>
          <Wrapper>
            <Header />
            {children}
            <Footer />
          </Wrapper>
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
